ALTER TABLE IF EXISTS form_b24
    ADD COLUMN IF NOT EXISTS confirmed BOOLEAN;

UPDATE form_b24
SET confirmed = FALSE
WHERE confirmed IS NULL;

ALTER TABLE IF EXISTS form_b24
    ALTER COLUMN confirmed SET DEFAULT FALSE;

ALTER TABLE IF EXISTS form_b24
    ALTER COLUMN confirmed SET NOT NULL;
